using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using ITControl.Infrastructure.Contexts;
using ITControl.Domain.Pages.Interfaces;
using ITControl.Infrastructure.Pages.Repositories;
using ITControl.Application.Pages.Interfaces;
using ITControl.Application.Pages.Services;
using ITControl.Application.Pages.Views;
using ITControl.Domain.Positions.Interfaces;
using ITControl.Infrastructure.Positions.Repositories;
using ITControl.Application.Positions.Interfaces;
using ITControl.Application.Positions.Services;
using ITControl.Application.Positions.Views;
using ITControl.Domain.Roles.Interfaces;
using ITControl.Infrastructure.Roles.Repositories;
using ITControl.Application.Roles.Interfaces;
using ITControl.Application.Roles.Services;
using ITControl.Application.Roles.Views;
using ITControl.Domain.Users.Interfaces;
using ITControl.Infrastructure.Users.Repositories;
using ITControl.Application.Users.Interfaces;
using ITControl.Application.Users.Services;
using ITControl.Application.Users.Views;
using ITControl.Domain.Units.Interfaces;
using ITControl.Infrastructure.Units.Repositories;
using ITControl.Application.Units.Interfaces;
using ITControl.Application.Units.Services;
using ITControl.Application.Units.Views;
using ITControl.Domain.Departments.Interfaces;
using ITControl.Infrastructure.Departments.Repositories;
using ITControl.Application.Departments.Interfaces;
using ITControl.Application.Departments.Services;
using ITControl.Application.Departments.Views;
using ITControl.Domain.Divisions.Interfaces;
using ITControl.Infrastructure.Divisions.Repositories;
using ITControl.Application.Divisions.Interfaces;
using ITControl.Application.Divisions.Services;
using ITControl.Application.Divisions.Views;
using ITControl.Domain.Locations.Interfaces;
using ITControl.Infrastructure.Locations.Repositories;
using ITControl.Application.Locations.Interfaces;
using ITControl.Application.Locations.Services;
using ITControl.Application.Locations.Views;
using ITControl.Domain.Contracts.Interfaces;
using ITControl.Infrastructure.Contracts.Repositories;
using ITControl.Application.Contracts.Interfaces;
using ITControl.Application.Contracts.Services;
using ITControl.Application.Contracts.Views;
using ITControl.Domain.Systems.Interfaces;
using ITControl.Infrastructure.Systems.Repositories;
using ITControl.Application.Systems.Interfaces;
using ITControl.Application.Systems.Services;
using ITControl.Application.Systems.Views;
using ITControl.Domain.Equipments.Interfaces;
using ITControl.Infrastructure.Equipments.Repositories;
using ITControl.Application.Equipments.Interfaces;
using ITControl.Application.Equipments.Services;
using ITControl.Application.Equipments.Views;
using ITControl.Domain.Calls.Interfaces;
using ITControl.Infrastructure.Calls.Repositories;
using ITControl.Application.Calls.Interfaces;
using ITControl.Application.Calls.Views;
using ITControl.Application.Calls.Services;
using ITControl.Domain.Treatments.Interfaces;
using ITControl.Infrastructure.Treatments.Repositories;
using ITControl.Application.Treatments.Interfaces;
using ITControl.Application.Treatments.Services;
using ITControl.Application.Treatments.Views;
using ITControl.Domain.Appointments.Interfaces;
using ITControl.Infrastructure.Appointments.Repositories;
using ITControl.Application.Appointments.Interfaces;
using ITControl.Application.Appointments.Services;
using ITControl.Application.Appointments.Views;
using ITControl.Application.Auth.Interfaces;
using ITControl.Application.Auth.Services;
using ITControl.Domain.Notifications.Interfaces;
using ITControl.Infrastructure.Notifications.Repositories;
using ITControl.Application.Notifications.Interfaces;
using ITControl.Application.Notifications.Services;
using ITControl.Application.Notifications.Views;
using ITControl.Application.Shared.Interfaces;
using ITControl.Application.Shared.Services;

namespace ITControl.CrossCutting.IoC;

public static class DependencyInjectionApi
{
    public static IServiceCollection AddInfrastructureApi(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        var connectionString = configuration.GetConnectionString("DefaultConnection");
        services.AddDbContext<ApplicationDbContext>(
            options => options.UseSqlServer(connectionString)
        );

        services.AddSingleton<IWebSocketService, WebSocketService>();

        services.AddScoped<IPositionsRepository, PositionsRepository>();
        services.AddScoped<IPositionsService, PositionsService>();
        services.AddScoped<IPositionsView, PositionsView>();
        services.AddScoped<IPagesRepository, PagesRepository>();
        services.AddScoped<IPagesService, PagesService>();
        services.AddScoped<IPagesView, PagesView>();
        services.AddScoped<IRolesRepository, RolesRepository>();
        services.AddScoped<IRolesPagesRepository, RolesPagesRepository>();
        services.AddScoped<IRolesService, RolesService>();
        services.AddScoped<IRolesView, RolesView>();
        services.AddScoped<IUsersRepository, UsersRepository>();
        services.AddScoped<IUsersEquipmentsRepository, UsersEquipmentsRepository>();
        services.AddScoped<IUsersSystemsRepository, UsersSystemsRepository>();
        services.AddScoped<IUsersService, UsersService>();
        services.AddScoped<IUsersView, UsersView>();
        services.AddScoped<IDepartmentsRepository, DepartmentsRepository>();
        services.AddScoped<IDepartmentsService, DepartmentsService>();
        services.AddScoped<IDepartmentsView, DepartmentsView>();
        services.AddScoped<IDivisionsRepository, DivisionsRepository>();
        services.AddScoped<IDivisionsService, DivisionsService>();
        services.AddScoped<IDivisionsView, DivisionsView>();
        services.AddScoped<IUnitsRepository, UnitsRepository>();
        services.AddScoped<IUnitsService, UnitsService>();
        services.AddScoped<IUnitsView, UnitsView>();
        services.AddScoped<IContractsRepository, ContractsRepository>();
        services.AddScoped<IContractsContactsRepository, ContractsContactsRepository>();
        services.AddScoped<IContractsService, ContractsService>();
        services.AddScoped<IContractsView, ContractsView>();
        services.AddScoped<ISystemsRepository, SystemsRepository>();
        services.AddScoped<ISystemsService, SystemsService>();
        services.AddScoped<ISystemsView, SystemsView>();
        services.AddScoped<ILocationsRepository, LocationsRepository>();
        services.AddScoped<ILocationsService, LocationsService>();
        services.AddScoped<ILocationsView, LocationsView>();
        services.AddScoped<IEquipmentsRepository, EquipmentsRepository>();
        services.AddScoped<IEquipmentsService, EquipmentsService>();
        services.AddScoped<IEquipmentsView, EquipmentsView>();
        services.AddScoped<IEquipmentsTypesView, EquipmentsTypesView>();
        services.AddScoped<ICallsRepository, CallsRepository>();
        services.AddScoped<ICallsStatusesRepository, CallsStatusesRepository>();
        services.AddScoped<ICallsService, CallsService>();
        services.AddScoped<ICallsView, CallsView>();
        services.AddScoped<ICallsStatusesView, CallsStatusesView>();
        services.AddScoped<ICallsReasonsView, CallsReasonsView>();
        services.AddScoped<ITreatmentsRepository, TreatmentsRepository>();
        services.AddScoped<ITreatmentsService, TreatmentsService>();
        services.AddScoped<ITreatmentsView, TreatmentsView>();
        services.AddScoped<ITreatmentsStatusesView, TreatmentsStatusesView>();
        services.AddScoped<ITreatmentsTypesView, TreatmentsTypesView>();
        services.AddScoped<IAppointmentsRepository, AppointmentsRepository>();
        services.AddScoped<IAppointmentsService, AppointmentsService>();
        services.AddScoped<IAppointmentsView, AppointmentsView>();
        services.AddScoped<INotificationsRepository, NotificationsRepository>();
        services.AddScoped<INotificationsService, NotificationsService>();
        services.AddScoped<INotificationsView, NotificationsView>();
        services.AddScoped<INotificationsTypesView, NotificationsTypesView>();
        services.AddScoped<INotificationsReferencesView, NotificationsReferencesView>();
        services.AddScoped<IAuthService, AuthService>();
        services.AddScoped<IUnitOfWork, UnitOfWork>();

        return services;
    }
}
