//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITControl.Application.Shared.Messages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ITControl.Application.Shared.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string APPOINTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPOINTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string AUTH_ROLE_INACTIVE {
            get {
                return ResourceManager.GetString("AUTH_ROLE_INACTIVE", resourceCulture);
            }
        }
        
        internal static string AUTH_INVALID_USER {
            get {
                return ResourceManager.GetString("AUTH_INVALID_USER", resourceCulture);
            }
        }
        
        internal static string AUTH_INACTIVE_USER {
            get {
                return ResourceManager.GetString("AUTH_INACTIVE_USER", resourceCulture);
            }
        }
        
        internal static string AUTH_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("AUTH_INVALID_PASSWORD", resourceCulture);
            }
        }
        
        internal static string CALL_NOT_FOUND {
            get {
                return ResourceManager.GetString("CALL_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string CALL_ROLE_MASTER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CALL_ROLE_MASTER_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string CONTRACT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CONTRACT_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string DEPARTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEPARTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string DIVISION_NOT_FOUND {
            get {
                return ResourceManager.GetString("DIVISION_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string EQUIPMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("EQUIPMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string LOCATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOCATION_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string NOTIFICATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("NOTIFICATION_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string PAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string PAGE_NAME_EXISTS {
            get {
                return ResourceManager.GetString("PAGE_NAME_EXISTS", resourceCulture);
            }
        }
        
        internal static string DIVISION_NAME_EXISTS {
            get {
                return ResourceManager.GetString("DIVISION_NAME_EXISTS", resourceCulture);
            }
        }
        
        internal static string DEPARTMENT_ALIAS_EXISTS {
            get {
                return ResourceManager.GetString("DEPARTMENT_ALIAS_EXISTS", resourceCulture);
            }
        }
        
        internal static string DEPARTMENT_NAME_EXISTS {
            get {
                return ResourceManager.GetString("DEPARTMENT_NAME_EXISTS", resourceCulture);
            }
        }
        
        internal static string POSITION_NOT_FOUND {
            get {
                return ResourceManager.GetString("POSITION_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string POSITION_DESCRIPTION_EXISTS {
            get {
                return ResourceManager.GetString("POSITION_DESCRIPTION_EXISTS", resourceCulture);
            }
        }
        
        internal static string ROLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ROLE_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string ROLE_NAME_EXISTS {
            get {
                return ResourceManager.GetString("ROLE_NAME_EXISTS", resourceCulture);
            }
        }
        
        internal static string ROLE_PAGES_NOT_FOUND {
            get {
                return ResourceManager.GetString("ROLE_PAGES_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string SYSTEM_NOT_FOUND {
            get {
                return ResourceManager.GetString("SYSTEM_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string TREATMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("TREATMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string UNIT_NOT_FOUND {
            get {
                return ResourceManager.GetString("UNIT_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string USER_USERNAME_EXISTS {
            get {
                return ResourceManager.GetString("USER_USERNAME_EXISTS", resourceCulture);
            }
        }
        
        internal static string USER_NAME_EXISTS {
            get {
                return ResourceManager.GetString("USER_NAME_EXISTS", resourceCulture);
            }
        }
        
        internal static string USER_EMAIL_EXISTS {
            get {
                return ResourceManager.GetString("USER_EMAIL_EXISTS", resourceCulture);
            }
        }
        
        internal static string USER_LOGGED_ID_REQUIRED {
            get {
                return ResourceManager.GetString("USER_LOGGED_ID_REQUIRED", resourceCulture);
            }
        }
        
        internal static string USER_LOGGED_ID_EQUALS {
            get {
                return ResourceManager.GetString("USER_LOGGED_ID_EQUALS", resourceCulture);
            }
        }
    }
}
