//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITControl.Application.Shared.Messages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITControl.Application.Shared.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agendamento não encontrado.
        /// </summary>
        internal static string APPOINTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("APPOINTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário inativo.
        /// </summary>
        internal static string AUTH_INACTIVE_USER {
            get {
                return ResourceManager.GetString("AUTH_INACTIVE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha inválida.
        /// </summary>
        internal static string AUTH_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("AUTH_INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário inválido.
        /// </summary>
        internal static string AUTH_INVALID_USER {
            get {
                return ResourceManager.GetString("AUTH_INVALID_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil inativo.
        /// </summary>
        internal static string AUTH_ROLE_INACTIVE {
            get {
                return ResourceManager.GetString("AUTH_ROLE_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chamado não encontrado.
        /// </summary>
        internal static string CALL_NOT_FOUND {
            get {
                return ResourceManager.GetString("CALL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil master não encontrado.
        /// </summary>
        internal static string CALL_ROLE_MASTER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CALL_ROLE_MASTER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Contrato não encontrado.
        /// </summary>
        internal static string CONTRACT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CONTRACT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma secretaria com esta sigla.
        /// </summary>
        internal static string DEPARTMENT_ALIAS_EXISTS {
            get {
                return ResourceManager.GetString("DEPARTMENT_ALIAS_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma secretaria com este nome.
        /// </summary>
        internal static string DEPARTMENT_NAME_EXISTS {
            get {
                return ResourceManager.GetString("DEPARTMENT_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Departamento não encontrado.
        /// </summary>
        internal static string DEPARTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEPARTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma divisão com este nome.
        /// </summary>
        internal static string DIVISION_NAME_EXISTS {
            get {
                return ResourceManager.GetString("DIVISION_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Divisão não encontrado.
        /// </summary>
        internal static string DIVISION_NOT_FOUND {
            get {
                return ResourceManager.GetString("DIVISION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Equipamento não encontrado.
        /// </summary>
        internal static string EQUIPMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("EQUIPMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Base de conhecimento não encontrada..
        /// </summary>
        internal static string KnowledgeBaseNotFound {
            get {
                return ResourceManager.GetString("KnowledgeBaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Localização não encontrado.
        /// </summary>
        internal static string LOCATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOCATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notificação não encontrada.
        /// </summary>
        internal static string NOTIFICATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("NOTIFICATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma página com este nome.
        /// </summary>
        internal static string PAGE_NAME_EXISTS {
            get {
                return ResourceManager.GetString("PAGE_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Página não encontrada.
        /// </summary>
        internal static string PAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("PAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um cargo com esta descrição.
        /// </summary>
        internal static string POSITION_DESCRIPTION_EXISTS {
            get {
                return ResourceManager.GetString("POSITION_DESCRIPTION_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo não encontrado.
        /// </summary>
        internal static string POSITION_NOT_FOUND {
            get {
                return ResourceManager.GetString("POSITION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um perfil com este nome.
        /// </summary>
        internal static string ROLE_NAME_EXISTS {
            get {
                return ResourceManager.GetString("ROLE_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil não encontrado.
        /// </summary>
        internal static string ROLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ROLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Páginas do perfil são obrigatórias.
        /// </summary>
        internal static string ROLE_PAGES_NOT_FOUND {
            get {
                return ResourceManager.GetString("ROLE_PAGES_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Suplemento não encontrado.
        /// </summary>
        internal static string SUPPLEMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SUPPLEMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Movimento de suprimento não encontrado..
        /// </summary>
        internal static string SupplementMovimentNotFound {
            get {
                return ResourceManager.GetString("SupplementMovimentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sistema não encontrado.
        /// </summary>
        internal static string SYSTEM_NOT_FOUND {
            get {
                return ResourceManager.GetString("SYSTEM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atendimento não emcontrado.
        /// </summary>
        internal static string TREATMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("TREATMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unidade não encontrada.
        /// </summary>
        internal static string UNIT_NOT_FOUND {
            get {
                return ResourceManager.GetString("UNIT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um usuário em este e-mail.
        /// </summary>
        internal static string USER_EMAIL_EXISTS {
            get {
                return ResourceManager.GetString("USER_EMAIL_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é permitido remover a si mesmo.
        /// </summary>
        internal static string USER_LOGGED_ID_EQUALS {
            get {
                return ResourceManager.GetString("USER_LOGGED_ID_EQUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O id do usuário logado é obrigatório.
        /// </summary>
        internal static string USER_LOGGED_ID_REQUIRED {
            get {
                return ResourceManager.GetString("USER_LOGGED_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um usuário com este nome.
        /// </summary>
        internal static string USER_NAME_EXISTS {
            get {
                return ResourceManager.GetString("USER_NAME_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado.
        /// </summary>
        internal static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um usuário com este nome de usuário.
        /// </summary>
        internal static string USER_USERNAME_EXISTS {
            get {
                return ResourceManager.GetString("USER_USERNAME_EXISTS", resourceCulture);
            }
        }
    }
}
