//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITControl.Application.Shared.Messages.Notifications {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Titles {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ITControl.Application.Shared.Messages.Notifications.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string APPOINTMENTS_STARTED {
            get {
                return ResourceManager.GetString("APPOINTMENTS_STARTED", resourceCulture);
            }
        }
        
        internal static string APPOINTMENTS_UPDATED {
            get {
                return ResourceManager.GetString("APPOINTMENTS_UPDATED", resourceCulture);
            }
        }
        
        internal static string CALLS_NEW {
            get {
                return ResourceManager.GetString("CALLS_NEW", resourceCulture);
            }
        }
        
        internal static string TREATMENTS_STARTED {
            get {
                return ResourceManager.GetString("TREATMENTS_STARTED", resourceCulture);
            }
        }
        
        internal static string TREATMENTS_UPDATED {
            get {
                return ResourceManager.GetString("TREATMENTS_UPDATED", resourceCulture);
            }
        }
    }
}
