//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITControl.Domain.Shared.Messages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ITControl.Domain.Shared.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MAX_LENGTH {
            get {
                return ResourceManager.GetString("MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string MIN_LENGTH {
            get {
                return ResourceManager.GetString("MIN_LENGTH", resourceCulture);
            }
        }
        
        public static string POSITIVE_VALUE {
            get {
                return ResourceManager.GetString("POSITIVE_VALUE", resourceCulture);
            }
        }
        
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
        
        public static string VALID_EMAIL {
            get {
                return ResourceManager.GetString("VALID_EMAIL", resourceCulture);
            }
        }
        
        public static string INVALID_DATE {
            get {
                return ResourceManager.GetString("INVALID_DATE", resourceCulture);
            }
        }
        
        public static string INVALID_TIME {
            get {
                return ResourceManager.GetString("INVALID_TIME", resourceCulture);
            }
        }
        
        public static string DATE_GREATER_THAN_CURRENT {
            get {
                return ResourceManager.GetString("DATE_GREATER_THAN_CURRENT", resourceCulture);
            }
        }
        
        public static string DATE_GREATER_THAN {
            get {
                return ResourceManager.GetString("DATE_GREATER_THAN", resourceCulture);
            }
        }
        
        public static string TIME_GREATER_THAN_CURRENT {
            get {
                return ResourceManager.GetString("TIME_GREATER_THAN_CURRENT", resourceCulture);
            }
        }
        
        public static string INVALID_GUID {
            get {
                return ResourceManager.GetString("INVALID_GUID", resourceCulture);
            }
        }
        
        public static string INVALID_BOOLEAN {
            get {
                return ResourceManager.GetString("INVALID_BOOLEAN", resourceCulture);
            }
        }
        
        public static string DATE_PRESENT_PAST {
            get {
                return ResourceManager.GetString("DATE_PRESENT_PAST", resourceCulture);
            }
        }
        
        public static string Parser_ToGuid_Invalid_GUID_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToGuid_Invalid_GUID_format___0_", resourceCulture);
            }
        }
        
        public static string Parser_ToEnum_Invalid_ENUM_value___0_ {
            get {
                return ResourceManager.GetString("Parser_ToEnum_Invalid_ENUM_value___0_", resourceCulture);
            }
        }
        
        public static string Parser_ToDateOnly_Invalid_DateOnly_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToDateOnly_Invalid_DateOnly_format___0_", resourceCulture);
            }
        }
        
        public static string Parser_ToTimeOnly_Invalid_TimeOnly_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToTimeOnly_Invalid_TimeOnly_format___0_", resourceCulture);
            }
        }
        
        public static string Parser_ToBool_Invalid_boolean_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToBool_Invalid_boolean_format___0_", resourceCulture);
            }
        }
    }
}
