//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITControl.Domain.Shared.Messages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITControl.Domain.Shared.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} com o id &apos;{1}&apos; não foi encontrado..
        /// </summary>
        public static string ConnectionNotFound {
            get {
                return ResourceManager.GetString("ConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior que a data atual.
        /// </summary>
        public static string DATE_GREATER_THAN {
            get {
                return ResourceManager.GetString("DATE_GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma data maior que {1}.
        /// </summary>
        public static string DATE_GREATER_THAN_CURRENT {
            get {
                return ResourceManager.GetString("DATE_GREATER_THAN_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma data menor ou igual a atual.
        /// </summary>
        public static string DATE_PRESENT_PAST {
            get {
                return ResourceManager.GetString("DATE_PRESENT_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um valor booleano válido.
        /// </summary>
        public static string INVALID_BOOLEAN {
            get {
                return ResourceManager.GetString("INVALID_BOOLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser uma data válida.
        /// </summary>
        public static string INVALID_DATE {
            get {
                return ResourceManager.GetString("INVALID_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um valor UUID válido.
        /// </summary>
        public static string INVALID_GUID {
            get {
                return ResourceManager.GetString("INVALID_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um horário válido.
        /// </summary>
        public static string INVALID_TIME {
            get {
                return ResourceManager.GetString("INVALID_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve conter até {1} caracteres.
        /// </summary>
        public static string MAX_LENGTH {
            get {
                return ResourceManager.GetString("MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve conter no mínimo {1} caracteres.
        /// </summary>
        public static string MIN_LENGTH {
            get {
                return ResourceManager.GetString("MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid boolean format: {0}.
        /// </summary>
        public static string Parser_ToBool_Invalid_boolean_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToBool_Invalid_boolean_format___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid DateOnly format: {0}.
        /// </summary>
        public static string Parser_ToDateOnly_Invalid_DateOnly_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToDateOnly_Invalid_DateOnly_format___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid ENUM value: {0}.
        /// </summary>
        public static string Parser_ToEnum_Invalid_ENUM_value___0_ {
            get {
                return ResourceManager.GetString("Parser_ToEnum_Invalid_ENUM_value___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid GUID format: {0}.
        /// </summary>
        public static string Parser_ToGuid_Invalid_GUID_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToGuid_Invalid_GUID_format___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid TimeOnly format: {0}.
        /// </summary>
        public static string Parser_ToTimeOnly_Invalid_TimeOnly_format___0_ {
            get {
                return ResourceManager.GetString("Parser_ToTimeOnly_Invalid_TimeOnly_format___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um número positivo.
        /// </summary>
        public static string POSITIVE_VALUE {
            get {
                return ResourceManager.GetString("POSITIVE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é obrigatório.
        /// </summary>
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser maior que o horário atual.
        /// </summary>
        public static string TIME_GREATER_THAN_CURRENT {
            get {
                return ResourceManager.GetString("TIME_GREATER_THAN_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} deve ser um e-mail válido.
        /// </summary>
        public static string VALID_EMAIL {
            get {
                return ResourceManager.GetString("VALID_EMAIL", resourceCulture);
            }
        }
    }
}
